# Generated by Django 2.2.13 on 2020-06-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='tz',
            field=models.CharField(help_text='Timezone', max_length=255),
        ),
    ]
